name: build windows executable
run-name: ${{ github.actor }} building windows executable
on: [push]
jobs:
  pyinstaller-build:
    runs-on: windows-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.13'
          spec: 'lpawards.py'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'lpawards.exe'
          options: --onefile, --name "lpawards", --windowed, 
