name: build mac executable
run-name: ${{ github.actor }} building mac executable
on: [push]
jobs:
  pyinstaller-build:
    runs-on: mac-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.13'
          spec: 'lpawards.py'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'lpawards.app'
          options: --onefile, --name "lpawards", 
